### ISSUE TITLE
Crash when used with The Witch class

### ISSUE THREAD

**Issue by KongMD-Steam** [spikeof2010/SpikesRelics#3]
The game crashes on launch when enabled with The Witch class mod. However, it only crashes when this mod is loaded before The Witch in the mod loading order. I suspect that it's because both mods have a relic named 'Toy Horse'.

### Mods used:
BaseMod
Spike's Relics
The Witch

### Crash log
[SlayTheSpire_log.zip](https://github.com/spikeof2010/SpikesRelics/files/2239081/SlayTheSpire_log.zip)

[The Witch's Toy Horse mod](https://github.com/gygrazok/witchmod/blob/master/src/main/java/witchmod/relics/ToyHorse.java)

**Comment by spikeof2010** [comment]
Should be renamed now, thanks for reporting this!
